LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE		:= init.qcom.power.rc
LOCAL_MODULE_TAGS	:= optional eng
LOCAL_MODULE_CLASS	:= ETC
LOCAL_SRC_FILES		:= etc/init.qcom.power.rc
LOCAL_MODULE_PATH	:= $(TARGET_ROOT_OUT)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE		:= cpu.conf
LOCAL_MODULE_TAGS	:= optional
LOCAL_MODULE_CLASS	:= ETC
LOCAL_SRC_FILES		:= etc/$(LOCAL_MODULE)
LOCAL_MODULE_PATH       := $(TARGET_OUT_ETC)/cpu
LOCAL_POST_INSTALL_CMD  := chmod 755 $(TARGET_OUT_ETC)/cpu/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)
